name: bus
description: A light-weight event bus implementing the pub-sub pattern.
version: 0.0.4
homepage: https://github.com/thekeenant/dart-bus
author: Keenan Thompson <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  test: ^0.12.0
